// generated by makeinfo

typedef enum {
MT_PLAYER,
MT_TROOP,
MT_POSSESSED,
MT_SHOTGUY,
MT_SERGEANT,
MT_HEAD,
MT_SKULL,
MT_BRUISER,
MT_SPIDER,
MT_CYBORG,
MT_BARREL,
MT_TROOPSHOT,
MT_HEADSHOT,
MT_BIGHEADSHOT,
MT_BRUISERSHOT,
MT_ROCKET,
MT_PLASMA1,
MT_PLASMA2,
MT_ARM1,
MT_ARM2,
NUMMOBJTYPES} mobjtype_t;

typedef struct {
	int	doomednum;
	int	spawnstate;
	int	spawnhealth;
	int	seestate;
	int	seesound;
	int	hearsound;
	int	painstate;
	int	painchance;
	int	painsound;
	int	meleestate;
	int	missilestate;
	int	deathstate;
	int	deathsound;
	int	speed;
	int	radius;
	int	height;
	int	points;
	int	damage;
	int	flags;
} mobjinfo_t;

extern mobjinfo_t mobjinfo[NUMMOBJTYPES];

