#!/bin/csh -fb

make	CC="cc"														\
		CFLAGS="-g -Wall -arch m68k -arch i386 -arch hppa" \
		LDFLAGS="-arch m68k -arch i386 -arch hppa" \
		OBJDIR="next_obj"											

#		LIBS="-lposix" \
#		CFLAGS="-g -Wall -D_POSIX_SOURCE -arch m68k -arch i386 -arch hppa" \
