// generated by makeinfo

#include "DoomDef.h"

mobjinfo_t mobjinfo[NUMMOBJTYPES] = {

{		// MT_PLAYER
-1,		// doomednum
S_PLAY_STND,		// spawnstate
1000,		// spawnhealth
S_PLAY_RUN1,		// seestate
0,		// seesound
0,		// hearsound
S_PLAY_PAIN,		// painstate
200,		// painchance
0,		// painsound
S_NULL,		// meleestate
S_PLAY_ATK1,		// missilestate
S_PLAY_DIE1,		// deathstate
0,		// deathsound
0,		// speed
16*FRACUNIT,		// radius
56*FRACUNIT,		// height
600,		// points
0,		// damage
0		// flags
 },

{		// MT_TROOP
3001,		// doomednum
S_TROO_STND,		// spawnstate
60,		// spawnhealth
S_TROO_RUN1,		// seestate
0,		// seesound
0,		// hearsound
S_TROO_PAIN,		// painstate
200,		// painchance
0,		// painsound
S_TROO_ATK1,		// meleestate
S_TROO_ATK1,		// missilestate
S_TROO_DIE1,		// deathstate
0,		// deathsound
8,		// speed
20*FRACUNIT,		// radius
56*FRACUNIT,		// height
600,		// points
0,		// damage
0		// flags
 },

{		// MT_POSSESSED
3004,		// doomednum
S_POSS_STND,		// spawnstate
20,		// spawnhealth
S_POSS_RUN1,		// seestate
0,		// seesound
0,		// hearsound
S_POSS_PAIN,		// painstate
200,		// painchance
0,		// painsound
0,		// meleestate
S_POSS_ATK1,		// missilestate
S_POSS_DIE1,		// deathstate
0,		// deathsound
8,		// speed
20*FRACUNIT,		// radius
56*FRACUNIT,		// height
200,		// points
0,		// damage
0		// flags
 },

{		// MT_SHOTGUY
9,		// doomednum
S_SPOS_STND,		// spawnstate
30,		// spawnhealth
S_SPOS_RUN1,		// seestate
0,		// seesound
0,		// hearsound
S_SPOS_PAIN,		// painstate
170,		// painchance
0,		// painsound
0,		// meleestate
S_SPOS_ATK1,		// missilestate
S_SPOS_DIE1,		// deathstate
0,		// deathsound
8,		// speed
20*FRACUNIT,		// radius
56*FRACUNIT,		// height
600,		// points
0,		// damage
0		// flags
 },

{		// MT_SERGEANT
3002,		// doomednum
S_SARG_STND,		// spawnstate
150,		// spawnhealth
S_SARG_RUN1,		// seestate
0,		// seesound
0,		// hearsound
S_SARG_PAIN,		// painstate
180,		// painchance
0,		// painsound
S_SARG_ATK1,		// meleestate
0,		// missilestate
S_SARG_DIE1,		// deathstate
0,		// deathsound
10,		// speed
30*FRACUNIT,		// radius
56*FRACUNIT,		// height
1500,		// points
0,		// damage
0		// flags
 },

{		// MT_HEAD
3005,		// doomednum
S_HEAD_STND,		// spawnstate
400,		// spawnhealth
S_HEAD_RUN1,		// seestate
0,		// seesound
0,		// hearsound
S_HEAD_PAIN,		// painstate
128,		// painchance
0,		// painsound
0,		// meleestate
S_HEAD_ATK1,		// missilestate
S_HEAD_DIE1,		// deathstate
0,		// deathsound
8,		// speed
31*FRACUNIT,		// radius
56*FRACUNIT,		// height
4000,		// points
0,		// damage
0		// flags
 },

{		// MT_SKULL
3006,		// doomednum
S_SKULL_STND,		// spawnstate
100,		// spawnhealth
S_SKULL_RUN1,		// seestate
0,		// seesound
0,		// hearsound
S_SKULL_PAIN,		// painstate
200,		// painchance
0,		// painsound
0,		// meleestate
S_SKULL_ATK1,		// missilestate
S_SKULL_DIE1,		// deathstate
0,		// deathsound
8,		// speed
16*FRACUNIT,		// radius
56*FRACUNIT,		// height
1000,		// points
0,		// damage
0		// flags
 },

{		// MT_BRUISER
3003,		// doomednum
S_BOSS_STND,		// spawnstate
1000,		// spawnhealth
S_BOSS_RUN1,		// seestate
0,		// seesound
0,		// hearsound
S_BOSS_PAIN,		// painstate
50,		// painchance
0,		// painsound
S_BOSS_ATK1,		// meleestate
S_BOSS_ATK1,		// missilestate
S_BOSS_DIE1,		// deathstate
0,		// deathsound
8,		// speed
24*FRACUNIT,		// radius
72*FRACUNIT,		// height
10000,		// points
0,		// damage
0		// flags
 },

{		// MT_SPIDER
7,		// doomednum
S_SPID_STND,		// spawnstate
2000,		// spawnhealth
S_SPID_RUN1,		// seestate
0,		// seesound
0,		// hearsound
S_SPID_RUN1,		// painstate
40,		// painchance
0,		// painsound
0,		// meleestate
S_SPID_RUN1,		// missilestate
S_SPID_DIE1,		// deathstate
0,		// deathsound
8,		// speed
60*FRACUNIT,		// radius
100*FRACUNIT,		// height
20000,		// points
0,		// damage
0		// flags
 },

{		// MT_CYBORG
16,		// doomednum
S_CYBER_STND,		// spawnstate
3000,		// spawnhealth
S_CYBER_RUN1,		// seestate
0,		// seesound
0,		// hearsound
S_CYBER_RUN1,		// painstate
20,		// painchance
0,		// painsound
0,		// meleestate
0,		// missilestate
S_CYBER_DIE1,		// deathstate
0,		// deathsound
8,		// speed
40*FRACUNIT,		// radius
110*FRACUNIT,		// height
30000,		// points
0,		// damage
0		// flags
 },

{		// MT_BARREL
2035,		// doomednum
S_BAR1,		// spawnstate
30,		// spawnhealth
0,		// seestate
0,		// seesound
0,		// hearsound
0,		// painstate
0,		// painchance
0,		// painsound
0,		// meleestate
0,		// missilestate
S_BEXP,		// deathstate
0,		// deathsound
0,		// speed
10*FRACUNIT,		// radius
32*FRACUNIT,		// height
0,		// points
0,		// damage
0		// flags
 },

{		// MT_TROOPSHOT
-1,		// doomednum
S_TBALL1,		// spawnstate
1000,		// spawnhealth
S_NULL,		// seestate
0,		// seesound
0,		// hearsound
S_NULL,		// painstate
0,		// painchance
0,		// painsound
S_NULL,		// meleestate
S_NULL,		// missilestate
S_TBALLX1,		// deathstate
0,		// deathsound
10*FRACUNIT,		// speed
16*FRACUNIT,		// radius
16*FRACUNIT,		// height
0,		// points
3,		// damage
0		// flags
 },

{		// MT_HEADSHOT
-1,		// doomednum
S_RBALL1,		// spawnstate
1000,		// spawnhealth
S_NULL,		// seestate
0,		// seesound
0,		// hearsound
S_NULL,		// painstate
0,		// painchance
0,		// painsound
S_NULL,		// meleestate
S_NULL,		// missilestate
S_RBALLX1,		// deathstate
0,		// deathsound
10*FRACUNIT,		// speed
16*FRACUNIT,		// radius
16*FRACUNIT,		// height
0,		// points
5,		// damage
0		// flags
 },

{		// MT_BIGHEADSHOT
-1,		// doomednum
S_BBALL1,		// spawnstate
1000,		// spawnhealth
S_NULL,		// seestate
0,		// seesound
0,		// hearsound
S_NULL,		// painstate
0,		// painchance
0,		// painsound
S_NULL,		// meleestate
S_NULL,		// missilestate
S_BBALLX1,		// deathstate
0,		// deathsound
10*FRACUNIT,		// speed
16*FRACUNIT,		// radius
16*FRACUNIT,		// height
0,		// points
8,		// damage
0		// flags
 },

{		// MT_BRUISERSHOT
-1,		// doomednum
S_GBALL1,		// spawnstate
1000,		// spawnhealth
S_NULL,		// seestate
0,		// seesound
0,		// hearsound
S_NULL,		// painstate
0,		// painchance
0,		// painsound
S_NULL,		// meleestate
S_NULL,		// missilestate
S_GBALLX1,		// deathstate
0,		// deathsound
10*FRACUNIT,		// speed
16*FRACUNIT,		// radius
16*FRACUNIT,		// height
0,		// points
8,		// damage
0		// flags
 },

{		// MT_ROCKET
-1,		// doomednum
S_ROCKET,		// spawnstate
1000,		// spawnhealth
S_NULL,		// seestate
0,		// seesound
0,		// hearsound
S_NULL,		// painstate
0,		// painchance
0,		// painsound
S_NULL,		// meleestate
S_NULL,		// missilestate
S_EXPLODE1,		// deathstate
0,		// deathsound
20*FRACUNIT,		// speed
16*FRACUNIT,		// radius
16*FRACUNIT,		// height
0,		// points
20,		// damage
0		// flags
 },

{		// MT_PLASMA1
-1,		// doomednum
S_GPBALL1,		// spawnstate
1000,		// spawnhealth
S_NULL,		// seestate
0,		// seesound
0,		// hearsound
S_NULL,		// painstate
0,		// painchance
0,		// painsound
S_NULL,		// meleestate
S_NULL,		// missilestate
S_GBALLX1,		// deathstate
0,		// deathsound
25*FRACUNIT,		// speed
16*FRACUNIT,		// radius
16*FRACUNIT,		// height
0,		// points
5,		// damage
0		// flags
 },

{		// MT_PLASMA2
-1,		// doomednum
S_TBALL1,		// spawnstate
1000,		// spawnhealth
S_NULL,		// seestate
0,		// seesound
0,		// hearsound
S_NULL,		// painstate
0,		// painchance
0,		// painsound
S_NULL,		// meleestate
S_NULL,		// missilestate
S_TBALLX1,		// deathstate
0,		// deathsound
31*FRACUNIT,		// speed
16*FRACUNIT,		// radius
16*FRACUNIT,		// height
0,		// points
5,		// damage
0		// flags
 },

{		// MT_ARM1
2018,		// doomednum
S_ARM1,		// spawnstate
1000,		// spawnhealth
S_NULL,		// seestate
0,		// seesound
0,		// hearsound
S_NULL,		// painstate
0,		// painchance
0,		// painsound
S_NULL,		// meleestate
S_NULL,		// missilestate
S_NULL,		// deathstate
0,		// deathsound
0,		// speed
16*FRACUNIT,		// radius
16*FRACUNIT,		// height
0,		// points
0,		// damage
TF_SPECIAL		// flags
 },

{		// MT_ARM2
2019,		// doomednum
S_ARM2,		// spawnstate
1000,		// spawnhealth
S_NULL,		// seestate
0,		// seesound
0,		// hearsound
S_NULL,		// painstate
0,		// painchance
0,		// painsound
S_NULL,		// meleestate
S_NULL,		// missilestate
S_NULL,		// deathstate
0,		// deathsound
0,		// speed
16*FRACUNIT,		// radius
16*FRACUNIT,		// height
0,		// points
0,		// damage
TF_SPECIAL		// flags
 }
};

